version: '3'
services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - 3000:3000  
    depends_on:
      - postgres   
  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    ports:
      - 5000:5432
    logging:
      driver: none 






